# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function for optimize likelihood with Geometric distribution,
#' using the parameterization E[Y] = 1 + \exp(X\beta + offset)
#' @param beta0  - inital guess
#' @param Y      - (n x 1) the observations >1
#' @param X      - (n x K) covariates
#' @param offset - (n x 1) the offset
optim_geomm <- function(beta0, Y, X, offset) {
    .Call('_cams_optim_geomm', PACKAGE = 'cams', beta0, Y, X, offset)
}

#' Function for optimize likelihood with constrainted Geometric distribution,
#' using the parameterization E[Y] = 1 + \exp(X\beta + offset) (if unconstrained)
#' However now the observations are constrainted to Y[i] \leq K[i]
#' @param beta0  - inital guess
#' @param Y      - (n x 1) the observations >1
#' @param X      - (n x K) covariates
#' @param K      - (n x 1) upper constraint on Y
#' @param offset - (n x 1) the offset
optim_geommc <- function(beta0, Y, X, K, offset) {
    .Call('_cams_optim_geommc', PACKAGE = 'cams', beta0, Y, X, K, offset)
}

#' dd_lgeom
#'
NULL

lgeo_cpp <- function(Y, Theta, logl = TRUE) {
    .Call('_cams_lgeo_cpp', PACKAGE = 'cams', Y, Theta, logl)
}

dd_lgeo_cpp <- function(Y, Theta) {
    .Call('_cams_dd_lgeo_cpp', PACKAGE = 'cams', Y, Theta)
}

dd_lgeom_cpp <- function(beta, Y, X, offset, calc_hess = TRUE) {
    .Call('_cams_dd_lgeom_cpp', PACKAGE = 'cams', beta, Y, X, offset, calc_hess)
}

dd_lgeomc_cpp <- function(beta, Y, X, offset, K, calc_hess = TRUE) {
    .Call('_cams_dd_lgeomc_cpp', PACKAGE = 'cams', beta, Y, X, offset, K, calc_hess)
}

lgeo_const_cpp <- function(Y, Theta, K, logl = TRUE) {
    .Call('_cams_lgeo_const_cpp', PACKAGE = 'cams', Y, Theta, K, logl)
}

ddlgeo_const_cpp <- function(Y, Theta, K, calc_ddlog = TRUE) {
    .Call('_cams_ddlgeo_const_cpp', PACKAGE = 'cams', Y, Theta, K, calc_ddlog)
}

